DB_CONFIG = {
    "database": "tpch", #dsb
    "user": "",
    "password": "",
    "host": "localhost",
    "port": "5432", 
}


COST_STRATEGY = "pg_explain"

FLATTEN_RULES = [
    "FILTER_INTO_JOIN",
    "FILTER_CORRELATE",
]


PUSHDOWN_RULES = ["JOIN_LEFT_UNION_TRANSPOSE","JOIN_RIGHT_UNION_TRANSPOSE","JOIN_PROJECT_BOTH_TRANSPOSE", "FILTER_INTO_JOIN", "FILTER_SCAN", "JOIN_REDUCE_EXPRESSIONS", "FILTER_PROJECT_TRANSPOSE", "FILTER_TABLE_FUNCTION_TRANSPOSE", "FILTER_AGGREGATE_TRANSPOSE", "SORT_JOIN_TRANSPOSE", "SEMI_JOIN_REMOVE"] 



LOCAL_RULES = [
    "AGGREGATE_VALUES",
    "JOIN_REDUCE_EXPRESSIONS",

    'AGGREGATE_EXPAND_DISTINCT_AGGREGATES',
    'AGGREGATE_PROJECT_MERGE', 
    'AGGREGATE_ANY_PULL_UP_CONSTANTS',
    'AGGREGATE_UNION_AGGREGATE',
    'AGGREGATE_REMOVE',
    
    'FILTER_REDUCE_EXPRESSIONS',
    
    'PROJECT_REDUCE_EXPRESSIONS',
    'PROJECT_CALC_MERGE',
    'PROJECT_MERGE',
    'PROJECT_REMOVE',
    'PROJECT_TO_CALC',

    'SORT_PROJECT_TRANSPOSE',
    'SORT_UNION_TRANSPOSE',
    'SORT_REMOVE_CONSTANT_KEYS',
    'SORT_REMOVE',
    'SORT_FETCH_ZERO_INSTANCE',

    'CALC_MERGE',
    'CALC_REMOVE',
    
    'AGGREGATE_INSTANCE',
    'FILTER_INSTANCE', 
    'JOIN_LEFT_INSTANCE',
    'JOIN_RIGHT_INSTANCE',
    'PROJECT_INSTANCE',
    'SORT_INSTANCE',
    'UNION_INSTANCE',
    'INTERSECT_INSTANCE',
    'MINUS_INSTANCE'
]
